// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLzTYwLPEUuyE7YcaNzE1alW3l7EEPYvc',
    appId: '1:579338479157:web:90e8e18815b180e13e737c',
    messagingSenderId: '579338479157',
    projectId: 'carousel-a996b',
    authDomain: 'carousel-a996b.firebaseapp.com',
    storageBucket: 'carousel-a996b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd07oPKs7mUx1x2ny_XWKoAPPe948KFIA',
    appId: '1:579338479157:android:ef2dae78f60bcccb3e737c',
    messagingSenderId: '579338479157',
    projectId: 'carousel-a996b',
    storageBucket: 'carousel-a996b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB71SAa1rXeETs9_Vo5X4OqBh3XB8MOPSo',
    appId: '1:579338479157:ios:3f07c649571bc13f3e737c',
    messagingSenderId: '579338479157',
    projectId: 'carousel-a996b',
    storageBucket: 'carousel-a996b.appspot.com',
    iosBundleId: 'com.carousel.firebase.example.carouselFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB71SAa1rXeETs9_Vo5X4OqBh3XB8MOPSo',
    appId: '1:579338479157:ios:c23ac95c6a9825643e737c',
    messagingSenderId: '579338479157',
    projectId: 'carousel-a996b',
    storageBucket: 'carousel-a996b.appspot.com',
    iosBundleId: 'com.carousel.firebase.example.carouselFirebase.RunnerTests',
  );
}
